export enum Lands {
  ALBIA = 'albia',
  BJORDLUND = 'bjordlund',
  EMURAI = 'emurai',
  GARRAD = 'garrad',
  HETHESKEIN = 'hetheskein',
  ITHRA = 'ithra',
  JUTLUND = 'jutlund',
  NEYWYLL = 'neywyll',
  QUAT = 'quat',
  RAJAPUN = 'rajapun',
  ULWYLL = 'ulwyll',
  UNTERLUND = 'unterlund',
  WYDMYN = 'wydmyn',
};
